---

name: 🐞 Bug report
description: Create a bug report to help us improve AdGuard VPN Browser Extension.
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Please answer the following questions for yourself before submitting an issue.
      description:
      options:
        - label: I am running the latest version
        - label: I checked the documentation and found no answer
        - label: I checked to make sure that this issue has not already been filed
    validations:
      required: true
  - type: input
    id: etx_version
    attributes:
      label: AdGuard VPN Browser Extension version
      description: What version of our extension are you running?
      placeholder: For example, 1.3.42
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: macOS Monterey
          - **Browser**: FireFox 108.0.1 (64-bit)
      value: |
          - OS:
          - Browser:
      render: markdown
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Issue Details
      description: What happened?
      placeholder: Please describe the steps to reproduce the issue you've experienced.
    validations:
      required: true
  - type: textarea
    id: how_it_looks
    attributes:
      label: Actual Behavior
      description:
      placeholder: A clear and concise description of what happened.
    validations:
      required: false
  - type: textarea
    id: how_it_should_be
    attributes:
      label: Expected Behavior
      description:
      placeholder: A clear description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: screens
    attributes:
      label: Screenshots
      description:
      placeholder: If applicable add screenshots explaining your problem.
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description:
      placeholder: Add any other context about the problem here.
    validations:
      required: false
