const ENABLED_MARKER_02 = 'rgba(0, 76, 51, 0.2)';
const ENABLED_MARKER_05 = 'rgba(0, 76, 51, 0.5)';
const SELECTED_ENABLED_MARKER = '#5a9c69';
const SELECTED_DISABLED_MARKER = '#3A3A3A';
const DISABLED_MARKER = 'rgba(50, 50, 50, 0.5)';
const ENABLED_TEXT = '#004C33';
const DISABLED_TEXT = '#3A3A3A';

const COLORS = {
    ENABLED_MARKER_02,
    ENABLED_MARKER_05,
    DISABLED_MARKER,
    SELECTED_ENABLED_MARKER,
    SELECTED_DISABLED_MARKER,
    ENABLED_TEXT,
    DISABLED_TEXT,
};

export default COLORS;
