---
version: 2
plan:
  project-key: ADGEXT
  key: AVINCRSPECS
  name: vpn-extension - increment version
variables:
  dockerNode: adguard/node-ssh:22.17--0

stages:
  - Increment:
      manual: false
      final: false
      jobs:
        - Increment

Increment:
  key: INCR
  other:
    clean-working-dir: true
  docker:
    image: ${bamboo.dockerNode}
    volumes:
      ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -alt

            pnpm increment
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.commit
        configuration:
          commitMessage: 'skipci: Automatic increment build number'
          selectedRepository: defaultRepository
  requirements:
    - adg-docker: 'true'

branches:
  create: manually
  delete: never
  link-to-jira: true

notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
