---
version: 2
plan:
  project-key: ADGEXT
  key: VPNBETASPECS
  name: vpn-extension - test
variables:
  dockerNode: adguard/node-ssh:22.14--0

stages:
  - Test:
      manual: false
      final: false
      jobs:
        - Test

Test:
  key: TEST
  other:
    clean-working-dir: true
  docker:
    image: ${bamboo.dockerNode}
    volumes:
      ${system.YARN_DIR}: "${bamboo.cacheYarn}"
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            # Exclude '--ignore-optional' from yarn arguments
            # This is needed for installing swc core optional dependencies properly
            # as swc is used by 'yarn test'
            originalYarnArgs="$bamboo_varsYarn"
            modifiedYarnArgs=$(echo "$originalYarnArgs" | sed 's/--ignore-optional//g')

            # Install dependencies
            yarn install ${modifiedYarnArgs}

            yarn lint
            yarn test

            # build with test API endpoints:
            # chrome.zip, edge.zip, opera.zip, firefox.zip
            STAGE_ENV=test \
            VPN_API_URL="${bamboo.devVpnApiUrl}" \
            AUTH_API_URL="${bamboo.devAuthApiUrl}" \
            FORWARDER_DOMAIN="${bamboo.devVpnForwarderDomain}" \
            yarn dev

            # build artifacts chrome.crx
            STAGE_ENV=test \
            yarn crx:dev

            # build with prod API endpoints
            # chrome-prod.zip, edge-prod.zip, opera-prod.zip, firefox-prod.zip
            STAGE_ENV=prod \
            VPN_API_URL="${bamboo.prodVpnApiUrl}" \
            AUTH_API_URL="${bamboo.prodAuthApiUrl}" \
            FORWARDER_DOMAIN="${bamboo.prodVpnForwarderDomain}" \
            yarn dev

            # build artifacts chrome-prod.crx
            STAGE_ENV=prod \
            yarn crx:dev
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -la

            echo "Size before cleanup:" && du -h | tail -n 1
            rm -rf node_modules
            echo "Size after cleanup:" && du -h | tail -n 1
  artifacts:
    - name: edge.zip
      location: build/dev
      pattern: edge.zip
      shared: true
      required: true
    - name: chrome.zip
      location: build/dev
      pattern: chrome.zip
      shared: true
      required: true
    - name: opera.zip
      location: build/dev
      pattern: opera.zip
      shared: true
      required: true
    - name: firefox.zip
      location: build/dev
      pattern: firefox.zip
      shared: true
      required: true
    - name: chrome.crx
      location: build/dev
      pattern: chrome.crx
      shared: true
      required: true
    - name: edge-prod.zip
      location: build/dev
      pattern: edge-prod.zip
      shared: true
      required: true
    - name: chrome-prod.zip
      location: build/dev
      pattern: chrome-prod.zip
      shared: true
      required: true
    - name: opera-prod.zip
      location: build/dev
      pattern: opera-prod.zip
      shared: true
      required: true
    - name: firefox-prod.zip
      location: build/dev
      pattern: firefox-prod.zip
      shared: true
      required: true
    - name: chrome-prod.crx
      location: build/dev
      pattern: chrome-prod.crx
      shared: true
      required: true
  requirements:
    - adg-docker: 'true'

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: true

notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
